### ISSUE TITLE
PhoneNumber missing documentation

### ISSUE THREAD

**Issue by dvaeversted** [clearhaus/3DSv2-api-documentation#7]
The section about the format for the PhoneNumber object is completely empty: https://clearhaus.github.io/3DSv2-api-documentation/reference.html?messageCategory=P&deviceChannel=BRW#phonenumber

**Comment by kse-clearhaus** [comment]
Fixed by: https://github.com/clearhaus/3DSv2-api-documentation/commit/2b9179911e3c068ea0bd6f435428a3bbc73f89a2

This of course leads to another issue, specifically a CSS one :man_facepalming: 

![2020-03-26-084107_1102x637_scrot](https://user-images.githubusercontent.com/34437910/77621877-8eeff480-6f3d-11ea-8f17-bcb982bbb927.png)
